### ISSUE TITLE
To-do item's time bar misaligned Despite having the same amount of time

### ISSUE THREAD

**Issue by ThomasJRyan** [ethanelliott/PersonalDashboard#23]
I see why this is the way it is. The countdown bar goes from when you added it. 

But when you add a due date that's the same as another one, the bars are misaligned.

I'm not sure how you'd fix this, but fix it!

Here's a picture to clarity

![uoitpd_2017-10-31_11-11-01](https://user-images.githubusercontent.com/18319621/32231676-9d4ad3b6-be2c-11e7-9cd7-00e89d3bb49c.png)

Despite them being due at the same time, the first bar is further along than the second since I added it about 10 hours later.

Could potentially fix this by making the bar default to only show up for a week in advance. Anything over a week doesn't move the bar and maybe makes it a nice blue colour (Think Majora's Mask Chateau Romani) 

Less than a week left - Starts to decrease proportionally to a week
![image](https://user-images.githubusercontent.com/18319621/32232038-7c9c92e8-be2d-11e7-8971-011b07c71f0d.png)

Over a week left - Doesn't decrease
![image](https://user-images.githubusercontent.com/18319621/32232055-85a87046-be2d-11e7-9fe7-35b4bc4bac00.png)

**Comment by ethanelliott** [comment]
This method of displaying the progress bar allows a user to visualize the time they have left, relative to the moment that they created the to-do. You may have 2 tasks in your to-do list, but one may have had 2 weeks to complete, whereas the other may have only had 2 days to complete. It would make more sense to show that you are closer to completing the 2 week project, because it would be assumed that that project will take more work, relative to the other to-do.
